### ISSUE TITLE
Split SFe64 for now 

### ISSUE THREAD

**Issue by sylvia-leaf** [SFe-Team-was-taken/SFe#3]
I think that the SFe64 might be too difficult for soundfont program developers to implement right now with all its differences from the SFe32, so maybe we should consider splitting it off into a different branch of the SFe format until SFe32 is widely adopted. This might not be done if necessary

**Comment by stgiga** [comment]
You might want to set it as a sort of milestone.

**Comment by sylvia-leaf** [comment]
We created two branches, SFe32-only and SFe64-only. Shortly, we will work on splitting the SFe32 and SFe64 specifications. 

When we are done, we'll:
- merge the SFe32-only branch into this repository
- rename this repository to "SFe32"
- make a new "SFe64" repository with the contents of the SFe64-only branch

We may also rework SFe64 into a format that is easy to support along with SFe32. Additional SFe64 features are less important than getting the SF format into 64 bits in the first place!

If anyone has objections to the idea then please tell us here.

**Comment by sylvia-leaf** [comment]
The initial draft is completed and can be found in the [SFe32-only](https://github.com/SFe-Team-was-taken/SFe/tree/SFe32-only) and [SFe64-only](https://github.com/SFe-Team-was-taken/SFe/tree/SFe64-only) branches, if there are any issues please notify me.
