### ISSUE TITLE
Decide structure of final specification

### ISSUE THREAD

**Issue by sylvia-leaf** [SFe-Team-was-taken/SFe#50]
The draft specification closely follows the legacy SF2.04 specification. It is necessary to adapt the structure to a final specification, and also include the program and compatibility specifications in the same document.

---

Update: this refers to the structure of the SPECIFICATION DOCUMENT, not the file format itself

**Comment by spessasus** [comment]
My proposal for the final structure stays the same. DLSification of the sound bank, *without* any sf2 stubs or anything like that: #6 

But if we need to follow the old sf2 structure, then there's nothing to discuss, really? We have no choice other than keeping it the same as is and stacking more and more chunks into the info chunk...

**Comment by spessasus** [comment]
Oh, alright. Then I suggest sticking to one .MD file to make it easy to simply `ctrl + F`. I can auto generate TOS with links if needed (like I did previously). 

My proposed structure is as follows

- The toc at the top for easy access
- General info
- - Preamble (introduction)
- - Changelog
- - Terminology
- - Credits (team, legacy sf2, etc.)
- - Other things not being the spec itself (license, disclaimers, special thanks, scope and purpose, etc.)
- File structure
- - Riff explanation
- - The structure specification itself, but *no generator values*. Essentially the chunks and what they store, as in number types.
- Enumerations
- - All modulator and generator enumerations and all flags with clear explanation of what they do (INCLUDE EQUATIONS FOR TIMECENTS, ETC.)
- - all flags with explanation of their function
- Synthesis process
- - Detailed description of the synthesis process itself
- - Synthesis model description
- - Modulator description
- - Global, local stuff, how it gets summed, etc.
- - MIDI behavior, such as how to respond to midi messages
- - NRPN too
- Error handling
- - All error handlings in the file itself
- - Same for midi. Such as, what if MIDI selects a bank that does not exist.

I hope this included everything.

Sorry for the misunderstanding :-)
