### ISSUE TITLE
.PDF human-readable version of the specification

### ISSUE THREAD

**Issue by sylvia-leaf** [SFe-Team-was-taken/SFe#64]
This is the human-readable version of the specification that most people will read and will serve a similar purpose to `SFSPEC24.PDF`.

**Comment by stgiga** [comment]
UnifontEX should be used, and it works best at 16px or multiples of it (so 12pt or multiples assuming Windows)

https://stgiga.github.io/UnifontEX/

**Comment by stgiga** [comment]
Oh and just so you know, UnifontEX now supports Unicode 15.1!

**Comment by sylvia-leaf** [comment]
This has been completed. The logos will come in RC2.
