### ISSUE TITLE
Add a link to documentation for TSC mode in the future

### ISSUE THREAD

**Issue by sylvia-leaf** [SFe-Team-was-taken/SFe#9]
We've temporarily removed TSC mode from SFe32 due to compatibility concerns. Before we can bring it back, original information from saga should be found and linked.

**Comment by stgiga** [comment]
He hates his creation so please undo the removal.

**Comment by sylvia-leaf** [comment]
I'm a little bit confused. Do you want me to include TSC mode, or to keep it removed? Either way, the TSC mode removal was intended to be temporary while we find a way to include it without making it confusing for an bank developer regarding compatibility.

**Comment by stgiga** [comment]
> I'm a little bit confused. Do you want me to include TSC mode, or to keep it removed? Either way, the TSC mode removal was intended to be temporary while we find a way to include it without making it confusing for an bank developer regarding compatibility.

I want it to remain.

**Comment by sylvia-leaf** [comment]
TSC mode has been moved to a separate specification, and won't be included in SFe for now. 

Original documentation from saga (OpenMPT) should still be linked, but to the TSC specification.
